name: letsencrypt
namespace: quintana
version: 0.0.1
author: Sylvain Boily
display_name: Let's encrypt
tags:
  - beta
  - application
debian_depends:
  - git
homepage: https://github.com/sboily/wazo-plugind-letsencrypt
